In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print('Setup completed!')

Setup completed!

In [46]:
df = pd.read_fwf('../data/breast-cancer.data', names=['class', 'age', 'menopause', 'tumor-size', 'inv-nodes', 'node-caps', 'def-malig', 'breast', 'breast-quad', 'irradiat'])

In [47]:
df

,class,age,menopause,tumor-size,inv-nodes,node-caps,def-malig,breast,breast-quad,irradiat
0,"no-recurrence-events,30-39,premeno,30-34,0-2,n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"no-recurrence-events,40-49,premeno,20-24,0-2,n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"no-recurrence-events,40-49,premeno,20-24,0-2,n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"no-recurrence-events,60-69,ge40,15-19,0-2,no,2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"no-recurrence-events,40-49,premeno,0-4,0-2,no,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
281,"recurrence-events,30-39,premeno,30-34,0-2,no,2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,"recurrence-events,30-39,premeno,20-24,0-2,no,3...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,"recurrence-events,60-69,ge40,20-24,0-2,no,1,ri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,"recurrence-events,40-49,ge40,30-34,3-5,no,3,le...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,"recurrence-events,50-59,ge40,30-34,3-5,no,3,le...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
cleaned_df = pd.DataFrame(columns=['class', 'age', 'menopause', 'tumor-size', 'inv-nodes', 'node-caps', 'def-malig', 'breast', 'breast-quad', 'irradiat'])
cleaned_df

Empty DataFrame
Columns: [class, age, menopause, tumor-size, inv-nodes, node-caps, def-malig, breast, breast-quad, irradiat]
Index: []

In [60]:
for i in range(df.shape[0]):
    cleaned_df.loc[i, :] = df['class'][i].split(',')

In [61]:
cleaned_df

,class,age,menopause,tumor-size,inv-nodes,node-caps,def-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
...,...,...,...,...,...,...,...,...,...,...
281,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
282,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
283,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
284,recurrence-events,40-49,ge40,30-34,3-5,no,3,left,left_low,no
285,recurrence-events,50-59,ge40,30-34,3-5,no,3,left,left_low,no

In [62]:
cleaned_df.to_csv('../data/breast-cancer-cleaned.csv')